@startuml UC_Administracao_SiGT
left to right direction

actor "Administrador do sistema" as adm

rectangle "SiGT - Administração" {
    usecase "Manter usuário no SiGT" as uc_manter
    usecase "Gerenciar permissões de acesso" as uc_permissoes
    usecase "Registrar log de alteração" as uc_log
}

adm -- uc_manter
adm -- uc_permissoes

uc_permissoes ..> uc_log : << Include >>
uc_manter ..> uc_log : << Include >>
@enduml