@startuml UC_Gerenciar_Perfil
left to right direction

actor "Orientando" as ori
actor "SUAP" as suap <<System>>

rectangle "SiGT - Perfil" {
    usecase "Gerenciar perfil do orientando" as uc_perfil
    usecase "Sincronizar dados oficiais" as uc_sinc
}

ori -- uc_perfil
uc_perfil ..> uc_sinc : << Include >>
uc_sinc -- suap : "RN01: Campos de visualização"
@enduml