@startuml ManterUsuarioSiGT

left to right direction

' Atores
actor "Usuário do sistema" as user
actor "Administrador" as adm

' Relacionamentos entre atores (herança)
user <|-- adm

package "Gestão de Usuários e Perfis" {
    usecase "Manter usuário\n no SiGT" as uc_manter_usuario

    adm -- uc_manter_usuario
}

@enduml
