@startuml GerenciarPerfilOrientando

left to right direction

' Atores
actor "Usuário do sistema" as user
actor "Usuários comuns" as common_user
actor "Orientando" as ori

' Relacionamentos entre atores (herança)
user <|-- common_user
common_user <|-- ori

package "Gestão de Usuários e Perfis" {
    usecase "Gerenciar perfil\n do orientando" as uc_gerenciar_perfil_orientando

    ori -- uc_gerenciar_perfil_orientando
}

@enduml
